---
title: "**Introduction to R and Reproducible Research**"
subtitle: "EFB 645/496: Spring 2026"
author: "**SYLLABUS**"
output: 
  html_document:
    theme: cosmo
    toc: true
    toc_depth: 4
    toc_float: true
---


## General Information

**Credits:** 2 | **Meets:** MW, 10:35-11:30am  | **Location:** Baker 309

### Instructors

|[Hyatt Green](https://www.esf.edu/faculty/green/index.php) |[Elie Gurarie](https://eligurarie.github.io/) |
|------------------------------|------------------------------|
| Email: hgreen@esf.edu | Email: egurarie@esf.edu |
| Phone: 315-470-4814 | Phone: 315-470-3817 |
| Office: 201 Illick Hall | Office: 206 Illick Hall |
| Office hours: W 1-2pm | Office hours: M 2-3pm |

Course materials webpage: https://eligurarie.github.io/EFB654/

---

## Course Description

Although technological advances and automation, from next-generation sequencing at the molecular scale to remote sensing of global phenomena at the macro-scale, have revolutionized research in many fields, they have also dramatically increased the size and number of typical datasets. R allows us to wield such large datasets and, thus, draw conclusions from potentially useful data in many cases. At the same time, scientists can also do a better job of ensuring validity of their analysis and communicating their results. The purpose of this course is to familiarize students with R and associated tools to a) allow handling and analysis of large or complex data and b) promote good practices for reproducible research.

R, a statistical programming language and environment, offers capabilities to analyze data sets, big or small. RMarkdown, an authoring format, allows you to embed your R work (data summaries, stats, plots, etc.) within plain text. The two are linked together by `knitr` which evaluates and translates any R code or results embedded in a RMarkdown document so it's readable by a translator (e.g. pdfLaTeX, pandoc). Separately, these programs are extremely useful, but using them together will, in the end, help you accomplish many of the following *research* objectives.

- Drastically improve reproducibility of your analyses
- Save hours, days, or weeks of your time by automating your analysis
- Improve your document's appearance which really does impress people
- Organizes your work and ideas so that they are more accessible to you or others
- Imbeds your analysis methods along side your raw data and final results so they can be evaluated as a single body of work simultaneously

These tools are also dramatically changing the way we communicate science for the better. Analyses can be more easily thoroughly criticized. Figures look better. Coauthors or colleagues don't have to depend on your honesty (or competency). They can take your data and your functions and easily demonstrate to themselves that you did things right or wrong *OR* make some of their own tweaks and show you why their way is better.

Because these tools can be difficult to learn, especially if you don't have any coding experience, this course is intended to get you over that initial hump so you can explore R's packages and RMarkdown's capabilities on your own. If you're ever discouraged and think that R is too difficult or may not be useful I want to emphasize the enormous competitive advantage you will have over someone without these skills when it comes to getting into graduate school, getting a postdoc, or even a tenure-track position.

### Course Organization

We'll start learning both R and RMarkdown simultaneously. Luckily, R Studio makes the RMarkdown part fairly easy (e.g., 'Knit') so we'll primarily be learning the R language. Learning R is sort of like learning a language like French, Spanish, etc.—you lose it unless you use it. Entonces, there will be frequent in class and out of class exercises in addition to the final project. See Section: Evaluation for a point break-down.

## Background and Motivation

Today's world is flooded with data ...we don't feel right sending students, especially ones that might stay in the sciences, out of ESF without the tools to analyze larger datasets. With the current pressing global issues, environmental scientists in particular will fall under intense scrutiny and need to have the tools to manage and analyze large, complex data sets, and communicate the results of their analyses in an effective and responsible way.

You're a grad student or undergrad involved in research that needs to crunch some data for a paper or your thesis. You're thinking that the final project for this course is a great way to analyze that difficult data set you just produced. This doesn't necessarily have to be a large data set. If you don't have any data from your own research you'll need to find some data to work with soon. You might have read in a recent paper that the analysis you want to recreate was done in R with so-and-so package. You might not have a clue what R is—you just heard it might be something you need to learn. You also have a laptop and have downloaded the required programs and packages for this course. You have lots of time and endless determination to learn R.

If you already use R regularly you will find this course a light refresher, but mostly boring. If this is you, consider giving up your seat for another student that has less experience with R—this course is in high demand.

## Skill Outcomes

### R
- Get data into and out of R
- Obtain data summaries
- Plot basic data summary plots
- Perform basic built-in statistical functions in R
- Understand basic model fitting and interpreting results
- Write unique R functions efficiently
- Know how R handles special data classes, like dates
- Understand that there are many highly specialized packages available through R
- Reach beyond course content to individualize R to your needs

### Reproducible Research
- Learn basic RMarkdown
- Demonstrate literate programming

## Prerequisites

There are no course prerequisites. Basic stats may be helpful at some points. Programming experience (Perl, Python, Matlab, C++, etc.) would be extremely helpful, but certainly not required since this course is designed to start at square one.

## Required Materials

A laptop. **Please attend the first lecture with the latest R and RStudio installed.** Also, install the required packages for R. Confirm proper install and that things are working properly before the first class.

### Is LaTeX required?

No. LaTeX is a type setting language that enables you to produce good-looking documents (PDFs) with R code and output embedded. I highly recommend you at least become familiar with LaTeX; however, its installation takes up a relatively large amount of memory (maybe 4-5 G or so). You will need LaTeX if you choose to make your final presentation using beamer.

## Use of AI

Use all the AI you need. It's great at generating code that's error free, good at explaining how that code works, but not great experimental design, bringing meaning to results, and a few other important steps where humans are useful, for the time being. I would check out RTutor if you haven't already (http://rtutor.ai).

## Evaluation

### Participation 50%

I expect active participation in all exercises and discussion. I may take attendance at some points, but mostly I'll be gauging student participation as we go.

### Final Project 50%

Your final project will consist of two components: the final written report and the final verbal presentation. You should start with data you produced, if possible. Ideally, I'd like your analysis through this course to end up in your thesis, or some other meaningful place. If you don't have any data of your own to work on, contact me and I might be able to help. **DO NOT** leave this project till the last minute. Start thinking about it today.

Near the beginning of the term we'll meet privately to discuss a dataset you've chosen to make sure it meets the course criteria. At this initial meeting, bring your first and second choices for a final project dataset. **If you don't have your own data, check out the resources in the Resources section of this syllabus**. Keep in mind you'll have to produce some real results from the data by the end of the term, so don't pick a dataset that's too large or complex. On the other hand, if you pick a dataset that's too simple (e.g., a 2×10 data frame), you likely won't be able to demonstrate R proficiency.

#### Important dates for the final project

| Deadline | Purpose | Materials Due |
|----------|---------|---------------|
| Feb 12 | Initial data meeting | 1-2 datasets |
| April 9-28 | Final Presentations | 12-15 minute presentation |
| May 6 | Final Project Due | Final Report |

#### Final Written Report 30%

The final report is the culmination of all your work in the course. In this document, you'll demonstrate most if not all of the course learning outcomes. It should be constructed using R and knitr and describe in clear detail the background, data collection, analysis methods, results, discussion, and conclusions of your chosen project.

Submit your final project with 1) your (knitted) **pdf** file (preferred, but HTML acceptable), 2) any data in an ".Rdata" file that your source document requires, and 3) your source document ".Rmd" that you used to create your final document.

#### Penalties for late work

| Hours Overdue | Penalty |
|---------------|---------|
| 24 | 20% |
| 48 | 50% |
| >48 | 100% (no credit given) |

#### Final Verbal Presentation 20%

Your verbal communication, more so than your content, will be evaluated through your final presentation. I prefer you use RMarkdown (through beamer, slidy, or IOslides) for your final presentation, but use PowerPoint if you must. Presentations should be **about 9 minutes leaving about 3 minutes for questions/discussion for a max of about 12 minutes total per presentation**. My hope is that these presentations will be given in-person.

Because we have to fit everybody in the allocated presentation days, make sure you are not delayed by technical difficulties. If you are first to present, please try to show up a few minutes early to set up your presentation.

You will not turn in your presentation for a grade.

It's possible undergrads will not have the opportunity to present due to time constraints. In this case, the final written report will be worth 50% of your grade.

## Students with Learning and Physical Disabilities

SUNY-ESF works with the Office of Disability Services (ODS) at Syracuse University, who is responsible for coordinating disability-related accommodations. Students can contact ODS at 804 University Avenue- Room 309, 315-443-4498 to schedule an appointment and discuss their needs and the process for requesting accommodations. Students may also contact the ESF Office of Student Affairs, 110 Bray Hall, 315-470-6660 for assistance with the process. To learn more about ODS, visit http://disabilityservices.syr.edu. Authorized accommodation forms must be in the instructor's possession one week prior to any anticipated accommodation. Since accommodations may require early planning and generally are not provided retroactively, please contact ODS as soon as possible.

## Academic Dishonesty Statement

Academic dishonesty in any form will not be tolerated. This includes, but is not limited to, turning in work that is not your own in its entirety, using unauthorized materials during tests or quizzes, aiding others in dishonest behavior, or any attempts to deceive the instructor about anything. Any participation in academic dishonesty will result in a failing grade.

Checks for plagarism from your peers and internet resources will be performed routinely. I'm actually pretty proud of my plagarism checker R scripts.

Academic dishonesty is a sign of disrespect and breach of trust between a student, one's fellow students, or the instructor(s). By registering for courses at ESF you acknowledge your awareness of the ESF Code of Student Conduct (http://www.esf.edu/students/handbook/StudentHB.05.pdf), in particular academic dishonesty includes but is not limited to plagiarism and cheating, and other forms of academic misconduct. The Academic Integrity Handbook contains further information and guidance (http://www.esf.edu/students/integrity/). Infractions of the academic integrity code may lead to academic penalties as per the ESF Grading Policy (http://www.esf.edu/provost/policies/documents/GradingPolicy.11.12.2013.pdf).

## Downloading R and RStudio

To download R visit: http://www.r-project.org/  
To download R Studio visit: http://www.rstudio.org

## Getting Started with R and RStudio

### Windows
On the Windows download page, click on base. Download the installer, Download the latest stable verison of R for Windows. It will take a few minutes to download, and I recommend you save it to your desktop (instead of running it directly from the web). Once the download is complete, double-click the icon to start the installation. Simple questions are posed during the installation. Accept the default settings.

### Mac OS X
The R Project page provides some helpful advice depending on your version of the Mac OS. Follow the instructions, and if there is a problem we can help you figure it out.

## Getting Started with LaTeX

### Downloading LaTeX

To download LaTeX visit: http://latex-project.org/ftp.html

## Download/Install Help

Do not contact me for help downloading and installing R or RStudio. I say this not because I'm an unhelpful SOB, but because you need to be able to figure this out on your own. But really, if you've tried all you can think of and then tried three more times and you're still SOL, contact me.

I'll be practically useless when it comes to trouble-shooting LaTeX installs. Although I've found LaTeX extremely useful in the past 11 years or so, it is not my forte. Fortunately, most of the time LaTeX downloads and installs integrate seamlessly with R Studio. We'll have to work together on solving any issues with LaTeX.

## Other Useful Resources

### Books

If you really want to get into it:

*The Structure and Interpretation of Computer Programs* by Harold Abelson and Gerald Jay Sussman

*Advanced R* by Hadley Wickham  
See: http://www.r-project.org/doc/bib/R-books.html

*R for Data Science* by Hadley Wickham  
See: https://r4ds.had.co.nz/index.html

*Handling and Processing Strings in R* by Gaston Sanchez  
See: http://gastonsanchez.com/Handling_and_Processing_Strings_in_R.pdf

### Blogs/Websites

#### R Resources

CRAN: http://r-project.org  
TaskViews: http://cran.r-project.org/web/views  
Advanced R: http://adv-r.had.co.nz  
Quick-R: http://www.statmethods.net  
R-bloggers: http://www.r-bloggers.com  
RTutor: http://rtutor.ai

#### Authoring Formats
R Markdown v2: http://rmarkdown.rstudio.com  
Beamer Theme Matrix: https://www.hartwork.org/beamer-theme-matrix/  
Slidify tutorial: https://www.uvm.edu/rsenr/vtcfwru/R/fledglings/14_Slideshows.html  
Another Slidify tutorial: http://slidify.github.io/workshops/tutorials/03/#21

#### Minimal Working Examples
Minimal Working Examples (general): http://stackoverflow.com/help/mcve  
Minimal Working Examples (from R-bloggers): http://www.r-bloggers.com/minimal-reproducible-examples/  
Minimal Working Examples (from StackOverflow): http://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example

#### Spatial Analysis
spatial cheatsheet: http://www.maths.lancs.ac.uk/~rowlings/Teaching/UseR2012/cheatsheet.html  
spatial tutorial: https://github.com/Robinlovelace/Creating-maps-in-R

#### Miscellaneous
Another R course for Python Programmers: https://ramnathv.github.io/pycon2014-r/  
Debugging in R: http://www.stats.uwo.ca/faculty/murdoch/software/debuggingR/  
qqplot2 quick reference: http://zevross.com/blog/2014/08/04/beautiful-plotting-in-r-a-ggplot2-cheatsheet-3/  
help on reshaping data: http://seananderson.ca/2013/10/19/reshape.html  
Ordination for Ecologists: http://ordination.okstate.edu  
Writing formulae: http://ww2.coastal.edu/kingw/statistics/R-tutorials/formulae.html  
R popularity: http://r4stats.com/2015/10/13/rexer-analytics-survey-results/  
Networks in R: http://kateto.net/network-visualization

### Data

Inside-R post: http://www.inside-r.org/howto/finding-data-internet  
rOpenSci: Packages to get data: http://ropensci.org/packages/